name: kamer_drive_final
description: "La plateforme de référence pour la location et l'achat de véhicules au Cameroun."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.5.0
  provider: ^6.1.5+1
  go_router: ^17.1.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  image_picker: ^1.2.1
  firebase_storage: ^13.1.0
  url_launcher: ^6.3.2
  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  firebase_messaging: 16.1.2
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/logo.png
    - assets/images/logo/icon.png
    - assets/images/logo/icon2.png
    - assets/images/onboard/rental.png
    - assets/images/onboard/sale.png
    - assets/images/onboard/carpool.png
    - assets/images/onboard/carpool2.png
    - assets/images/onboard/welcome.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo.png"

flutter_native_splash:
  color: "#FFFFFF" 
  image: "assets/images/logo/icon2.png"
  android: false
  ios: false
  android_12:
    image: "assets/images/logo/icon2.png"
    color: "#FFFFFF" 