// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAGxZMRNdX91OCNhuIAD6bBmSW_thsldQ',
    appId: '1:144439760990:web:d68ddd6ae7217cf1247ccf',
    messagingSenderId: '144439760990',
    projectId: 'kamer-drive',
    authDomain: 'kamer-drive.firebaseapp.com',
    storageBucket: 'kamer-drive.firebasestorage.app',
    measurementId: 'G-3J7V15E8NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9xwScjB3Q1KnHvdpi5U-6-iGX-cZDKiA',
    appId: '1:144439760990:android:5a582f442dba1d3b247ccf',
    messagingSenderId: '144439760990',
    projectId: 'kamer-drive',
    storageBucket: 'kamer-drive.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeF0TdhTjH9ZEd91mSC_6zWuXySyXYMyA',
    appId: '1:144439760990:ios:2df983232ddc8f9f247ccf',
    messagingSenderId: '144439760990',
    projectId: 'kamer-drive',
    storageBucket: 'kamer-drive.firebasestorage.app',
    iosBundleId: 'com.example.kamerDriveFinal',
  );
}
