// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2SnVvly9D6txy-RdY6ZzYZRmIzk4VVKg',
    appId: '1:767758392521:web:3c1752204d41f187fd4118',
    messagingSenderId: '767758392521',
    projectId: 'kamer-drive-29b2b',
    authDomain: 'kamer-drive-29b2b.firebaseapp.com',
    storageBucket: 'kamer-drive-29b2b.firebasestorage.app',
    measurementId: 'G-02YBWPFHH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKmbaOn8SQWDNd9W3fap6gSrSLFyKnTco',
    appId: '1:767758392521:android:9ce7b7569145bafffd4118',
    messagingSenderId: '767758392521',
    projectId: 'kamer-drive-29b2b',
    storageBucket: 'kamer-drive-29b2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6gb-LqoaSsgf1O1PHABp4TMJLQ5Vu3_8',
    appId: '1:767758392521:ios:e32385c11388efaffd4118',
    messagingSenderId: '767758392521',
    projectId: 'kamer-drive-29b2b',
    storageBucket: 'kamer-drive-29b2b.firebasestorage.app',
    iosBundleId: 'com.example.kamerDriveFinal',
  );

}