// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2VeOb2PH6DIakmOTRFIyGnspNRww7XyE',
    appId: '1:202489626299:web:712d5901b9f031bd36b39e',
    messagingSenderId: '202489626299',
    projectId: 'kamer-drive-41b9b',
    authDomain: 'kamer-drive-41b9b.firebaseapp.com',
    storageBucket: 'kamer-drive-41b9b.firebasestorage.app',
    measurementId: 'G-5ZSV8JQD2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj-8NtzOTSyK8bwUUXlViXwQ9UzglzD5M',
    appId: '1:202489626299:android:a88481d486537d3636b39e',
    messagingSenderId: '202489626299',
    projectId: 'kamer-drive-41b9b',
    storageBucket: 'kamer-drive-41b9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Cy0X-HvlfYdkWPIHiNrLL2jCpRMA2u8',
    appId: '1:202489626299:ios:37b0aef5f5252c8736b39e',
    messagingSenderId: '202489626299',
    projectId: 'kamer-drive-41b9b',
    storageBucket: 'kamer-drive-41b9b.firebasestorage.app',
    iosBundleId: 'com.example.kamerDriveFinal',
  );
}
